// <auto-generated />
using APIDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116095832_SeedDb")]
    partial class SeedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIDemo.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pizza",
                            Price = 21.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Noodle Soup",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grilled Salmon",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pasta Carbonara",
                            Price = 16.99m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cake",
                            Price = 9.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
